package DigitalJournal;

public enum EmployeesNames {
    ETHAN_JOHNSON("Ethan Johnson"),
    EMMA_DAVIS("Emma Davis"),
    OLIVIA_WILLIAMS("Olivia Williams"),
    LIAM_MILLER("Liam Miller"),
    NOAH_MOORE("Noah Moore"),
    AVA_ROBINSON("Ava Robinson"),
    ISABELLA_THOMPSON("Isabella Thompson"),
    SOPHIA_WRIGHT("Sophia Wright"),
    JACKSON_MITCHELL("Jackson Mitchell"),
    AIDEN_SCOTT("Aiden Scott"),
    LUCAS_PHILLIPS("Lucas Phillips"),
    HARPER_ADAMS("Harper Adams"),
    HENRY_NELSON("Henry Nelson"),
    SAMUEL_TURNER("Samuel Turner"),
    ELIJAH_HARRIS("Elijah Harris"),
    ABIGAIL_BAKER("Abigail Baker"),
    BENJAMIN_WARD("Benjamin Ward"),
    DANIEL_EVANS("Daniel Evans"),
    MATTHEW_HALL("Matthew Hall"),
    CHARLOTTE_MARTINEZ("Charlotte Martinez"),
    ALEXANDER_MURPHY("Alexander Murphy"),
    EMILY_HAYES("Emily Hayes"),
    JAMES_COOPER("James Cooper"),
    SCARLETT_MARTINEZ("Scarlett Martinez"),
    DAVID_POWELL("David Powell"),
    MICHAEL_PETERSON("Michael Peterson"),
    JOSEPH_KELLY("Joseph Kelly"),
    CARTER_RIVERA("Carter Rivera"),
    OWEN_LONG("Owen Long"),
    EVELYN_WRIGHT("Evelyn Wright"),
    GRACE_HUGHES("Grace Hughes"),
    LUCAS_HAYES("Lucas Hayes"),
    CHLOE_SIMMONS("Chloe Simmons"),
    LILY_ALEXANDER("Lily Alexander"),
    SOPHIA_FOSTER("Sophia Foster"),
    ANTHONY_PERRY("Anthony Perry"),
    ELLA_YOUNG("Ella Young"),
    NATALIE_HUGHES("Natalie Hughes"),
    NOAH_TURNER("Noah Turner"),
    MASON_TURNER("Mason Turner"),
    ADDISON_DIAZ("Addison Diaz"),
    SAMUEL_TAYLOR("Samuel Taylor"),
    AMELIA_PETERSON("Amelia Peterson"),
    ARIA_TURNER("Aria Turner"),
    DYLAN_TORRES("Dylan Torres"),
    MIA_MORGAN("Mia Morgan"),
    JACK_RODRIGUEZ("Jack Rodriguez"),
    AVERY_HAYES("Avery Hayes"),
    LIAM_PHILLIPS("Liam Phillips"),
    GRACE_WRIGHT("Grace Wright"),
    BENJAMIN_LEWIS("Benjamin Lewis"),
    ELLA_KING("Ella King"),
    ANDREW_BROWN("Andrew Brown"),
    CLAIRE_TURNER("Claire Turner"),
    OLIVER_WRIGHT("Oliver Wright"),
    ZOEY_GONZALEZ("Zoey Gonzalez"),
    LINCOLN_DAVIS("Lincoln Davis"),
    PENELOPE_ROBINSON("Penelope Robinson"),
    HAZEL_TURNER("Hazel Turner"),
    LOGAN_NELSON("Logan Nelson"),
    LAYLA_DIAZ("Layla Diaz"),
    CALEB_YOUNG("Caleb Young"),
    SCARLETT_MITCHELL("Scarlett Mitchell"),
    AIDEN_HALL("Aiden Hall"),
    HARPER_MURPHY("Harper Murphy"),
    EVELYN_KING("Evelyn King"),
    AUBREY_TORRES("Aubrey Torres"),
    JONATHAN_YOUNG("Jonathan Young"),
    PEYTON_SCOTT("Peyton Scott"),
    ISAAC_DIAZ("Isaac Diaz"),
    LUCY_TURNER("Lucy Turner"),
    OWEN_TURNER("Owen Turner"),
    LILA_RODRIGUEZ("Lila Rodriguez"),
    JACKSON_PETERSON("Jackson Peterson"),
    AURORA_KING("Aurora King"),
    DAVID_ADAMS("David Adams"),
    LILY_SCOTT("Lily Scott"),
    WYATT_TORRES("Wyatt Torres"),
    ELEANOR_YOUNG("Eleanor Young"),
    GRAYSON_TURNER("Grayson Turner"),
    SAVANNAH_MITCHELL("Savannah Mitchell"),
    DANIEL_TORRES("Daniel Torres"),
    HANNAH_NELSON("Hannah Nelson"),
    NATHAN_WRIGHT("Nathan Wright"),
    STELLA_TURNER("Stella Turner"),
    LEO_LEWIS("Leo Lewis"),
    VICTORIA_TORRES("Victoria Torres"),
    ELIJAH_NELSON("Elijah Nelson"),
    NORA_TURNER("Nora Turner"),
    NICHOLAS_THOMPSON("Nicholas Thompson"),
    ZOE_HARRIS("Zoe Harris"),
    CALEB_TURNER("Caleb Turner"),
    AURORA_HAYES("Aurora Hayes"),
    ISAAC_TURNER("Isaac Turner"),
    JOSEPH_DAVIS("Joseph Davis"),
    ELIANA_TURNER("Eliana Turner");

    private String Ename;

    EmployeesNames(String name) {
        Ename = name;
    }

    public String getEname() {
        return Ename;
    }
}